# Generated by Django 4.0.1 on 2022-02-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='address',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prof',
            name='name',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prof',
            name='phone',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
