# Generated by Django 4.0.1 on 2022-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_prof_address_prof_name_prof_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='img',
            field=models.ImageField(upload_to='products'),
        ),
    ]
