# Generated by Django 4.0.1 on 2022-03-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_alter_product_fid'),
        ('users', '0004_alter_prof_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.product')),
            ],
        ),
    ]
