# Generated by Django 4.0.1 on 2022-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='status',
            field=models.TextField(default='Not activated', max_length=50),
        ),
    ]
