# Generated by Django 4.0.1 on 2022-02-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
