# Generated by Django 4.0.1 on 2022-02-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.TextField(max_length=300)),
                ('price', models.TextField()),
                ('quantity', models.TextField()),
                ('description', models.TextField(max_length=500)),
                ('med_img', models.ImageField(upload_to='')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.sellers')),
            ],
        ),
    ]
